# Generated by Django 6.0.6 on 2026-06-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_teammembership_alter_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('companies.team',),
        ),
    ]
