# Generated by Django 6.0.6 on 2026-06-21 08:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_job_title'),
        ('companies', '0008_teammessage'),
        ('dashboard', '0002_teammessage_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date', 'created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('companies.task',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
