# Generated by Django 6.0.6 on 2026-06-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_kanbancard_taskchecklistitem'),
        ('dashboard', '0003_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
            ],
            options={
                'verbose_name': 'Kanban Card',
                'verbose_name_plural': 'Kanban Cards',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('companies.kanbancard',),
        ),
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
            ],
            options={
                'verbose_name': 'Checklist Item',
                'verbose_name_plural': 'Checklist Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('companies.taskchecklistitem',),
        ),
    ]
