# Generated by Django 6.0.6 on 2026-06-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=20),
        ),
    ]
