# Generated by Django 6.0.6 on 2026-06-19 11:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Team = apps.get_model('companies', 'Team')
    TeamMembership = apps.get_model('companies', 'TeamMembership')
    user_model = settings.AUTH_USER_MODEL.split('.')
    app_label = user_model[0] if len(user_model) > 1 else 'accounts'
    model_name = user_model[-1] if len(user_model) > 1 else settings.AUTH_USER_MODEL
    User = apps.get_model(app_label, model_name)

    for team in Team.objects.all():
        existing_members = []
        if hasattr(team, 'members_through'):
            existing_members = list(team.members_through.all())
        elif hasattr(team, 'members'):
            existing_members = list(team.members.all())
        for user in existing_members:
            TeamMembership.objects.get_or_create(team=team, user=user, defaults={'role': 'Member'})


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_activitylog_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='Member', max_length=120)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at', 'user__first_name', 'user__last_name'],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
