# Generated by Django 6.0.6 on 2026-06-19 12:08

from django.conf import settings
from django.db import migrations


def forwards(apps, schema_editor):
    Team = apps.get_model('companies', 'Team')
    TeamMembership = apps.get_model('companies', 'TeamMembership')

    for team in Team.objects.all():
        for user in team.members.all():
            TeamMembership.objects.get_or_create(team=team, user=user, defaults={'role': 'Member'})


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_teammembership_alter_team_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS companies_teammembership (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                role varchar(120) NOT NULL DEFAULT 'Member',
                joined_at datetime NOT NULL,
                team_id bigint NOT NULL REFERENCES companies_team(id) DEFERRABLE INITIALLY DEFERRED,
                user_id bigint NOT NULL REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE(team_id, user_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS companies_teammembership;",
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
